# Human readable name of this type
name: Services

# Lowercase, underscored handle used to access this type
slug: services

# Explanatory text displayed in the back-office
description: A description of the content type for the editors

# Slug of field used to identify entries by default, such as the title
label_field_name: name

# Valid values: manually, created_at, updated_at, or the slug of any field
order_by: manually

# Valid values: asc (ascending) and desc (descending). Set to asc by default.
# order_direction: asc

# Specify a field slug to group entries by that field in the back-office.
# group_by: <your field>

# Activate public 'create' API (e.g for a contact form)
# public_submission_enabled: false

# Array of emails to be notified of new entries made with the public API
# public_submission_accounts: ['john@example.com']

# Control the display of the content type in the back-office.
# display_settings:
#   seo: false              # display the SEO tab for the content entries
#   advanced: false         # display the Advanced tab for the content entries
#   position: 1             # position in the sidebar menu
#   hidden: false           # hidden for authors?

# By default, the back-office displays the _label property (see label_field_name) of the content entry. This can be modified by writing your own Liquid template below:
# entry_template: '<a href="{{ link }}">{{ entry._label }}</a>' # The default template

# A list describing each field
fields: 
- name: # The lowercase, underscored name of the field
    label: Name # Human readable name of the field
    type: string
    required: true
    hint: Explanatory text displayed in the back office
    localized: false

- abriviated_name: # The lowercase, underscored name of the field
    label: Abriviated name # Human readable name of the field
    type: string
    required: false
    hint: Explanatory text displayed in the back office
    localized: false

- time: # The lowercase, underscored name of the field
    label: Time # Human readable name of the field
    type: string
    required: false
    hint: Explanatory text displayed in the back office
    localized: false

- day: # The lowercase, underscored name of the field
    label: Day # Human readable name of the field
    type: select
    required: false
    hint: Explanatory text displayed in the back office
    localized: false    # if localized, use
    #   en: ['option1_en', 'option2_en']
    #   fr: ['option1_fr', 'option2_fr']
    select_options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

- frequency: # The lowercase, underscored name of the field
    label: Frequency # Human readable name of the field
    type: select
    required: false
    hint: Frequency of the service
    localized: false
    select_options: ['Weekly', 'Monthly', 'Other']

- regular: # The lowercase, underscored name of the field
    label: Regular service # Human readable name of the field
    type: boolean
    required: false
    hint: This will show the service on the homepage
    localized: false
    select_options: ['option 1', 'option 2', 'option 3']

- teaser: # The lowercase, underscored name of the field
    label: Teaser # Human readable name of the field
    type: text
    required: false
    hint: Explanatory text displayed in the back office
    localized: false
    text_formatting: markdown # html (uses rich text editor), markdown or text (uses plain text editor)

- about: # The lowercase, underscored name of the field
    label: About # Human readable name of the field
    type: text
    required: false
    hint: Explanatory text displayed in the back office
    localized: false
    text_formatting: markdown # html (uses rich text editor), markdown or text (uses plain text editor)

- photo: # The lowercase, underscored name of the field
    label: Photo # Human readable name of the field
    type: file
    required: false
    hint: Explanatory text displayed in the back office
    localized: false

- logo: # The lowercase, underscored name of the field
    label: Logo # Human readable name of the field
    type: file
    required: false
    hint: Explanatory text displayed in the back office
    localized: false

- sermons: # The lowercase, underscored name of the field
    label: Sermons # Human readable name of the field
    type: has_many
    required: false
    hint: Explanatory text displayed in the back office
    localized: false    # Define the slug of the target content type (eg. comments)
    class_name: sermons
    # Define the name of the field referring to Services in the target content type (eg. post)
    inverse_of: service
    # If you want to manage the entries of the relationship directly from the source entry
    ui_enabled: false
    
